export enum types {
    LOAD_NEGOCIATION = "@pj/NEGOCIATION/LOAD_NEGOCIATION",
    LOAD_NEGOCIATION_INIT = "@pj/NEGOCIATION/LOAD_NEGOCIATION_INIT",
    LOAD_NEGOCIATION_SUCCESS = "@pj/NEGOCIATION/LOAD_NEGOCIATION_SUCCESS",
    LOAD_NEGOCIATION_FAILURE = "@pj/NEGOCIATION/LOAD_NEGOCIATION_FAILURE",

    ADD_NEGOCIATION = "@pj/NEGOCIATION/ADD_NEGOCIATION",
    ADD_NEGOCIATION_INIT = "@pj/NEGOCIATION/ADD_NEGOCIATION_INIT",
    ADD_NEGOCIATION_SUCCESS = "@pj/NEGOCIATION/ADD_NEGOCIATION_SUCCESS",
    ADD_NEGOCIATION_FAILURE = "@pj/NEGOCIATION/ADD_NEGOCIATION_FAILURE",

    REMOVE_NEGOCIATION = "@pj/NEGOCIATION/REMOVE_NEGOCIATION",
    REMOVE_NEGOCIATION_INIT = "@pj/NEGOCIATION/REMOVE_NEGOCIATION_INIT",
    REMOVE_NEGOCIATION_SUCCESS = "@pj/NEGOCIATION/REMOVE_NEGOCIATION_SUCCESS",
    REMOVE_NEGOCIATION_FAILURE = "@pj/NEGOCIATION/REMOVE_NEGOCIATION_FAILURE",

    UPDATE_NEGOCIATION = "@pj/NEGOCIATION/UPDATE_NEGOCIATION",
    UPDATE_NEGOCIATION_INIT = "@pj/NEGOCIATION/UPDATE_NEGOCIATION_INIT",
    UPDATE_NEGOCIATION_SUCCESS = "@pj/NEGOCIATION/UPDATE_NEGOCIATION_SUCCESS",
    UPDATE_NEGOCIATION_FAILURE = "@pj/NEGOCIATION/UPDATE_NEGOCIATION_FAILURE",
}

export interface Negociation {
    id: string;
    assessoria: string;
    atenuador: number;
    desconto: number;
    idadeDivida: number;
    juros: number;
    maximoParcela: number;
    multa?: number;
    reajuste: number;
    createdAt?: Date;
    updatedAt?: Date;
}

export interface ById {
    [key: string]: object;
}

export interface StateNegociation {
    byId: ById;
    allId: string[];
}
